//! Reconstructed opening as a set of assertions (§10.7).
//!
//! The log is append-only: events written before the `assertions`
//! field was introduced must remain readable without migration. This is
//! verified using JSON **written by hand in the test**, rather than generated
//! by the current code: a sample generated by the current code would test itself
//! and would pass even after an incompatible schema change (§15.7).

use iaam_core::event::Event;
use iaam_core::event::kind::{
    BasisCertainty, Certainty, DateCertainty, EventKind, Knowledge, OpeningAssertions, Tristate,
};

/// A version 2 event in the form in which it exists in previously created
/// databases: it has no `assertions` field.
///
/// The field formats (the date as a pair of “year and day of year,” the quantity as a string)
/// come from the current serialization — this is the format, not the expected
/// value. The assertion being tested was written by hand: the `kind` section
/// **does not contain** `assertions`, which is precisely what makes the sample a record
/// from the previous version rather than fresh output from the current code.
const RECORDED_AT_VERSION_TWO: &str = r#"{
  "id": "6f1a2b3c-4d5e-4f60-8112-233445566778",
  "schema_version": 2,
  "owner": "11111111-2222-4333-8444-555555555555",
  "account": "aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee",
  "kind": {
    "OpeningPosition": {
      "instrument": "99999999-8888-4777-8666-555555555555",
      "quantity": "10",
      "cost_basis": null
    }
  },
  "dates": {
    "trade": null,
    "settled": null,
    "cash_posted": [2024, 61],
    "entitlement": null,
    "paid": null,
    "tax_period_override": null
  },
  "order": { "date": [2024, 61], "sequence": 1 },
  "legs": [],
  "provenance": {
    "source": "12121212-3434-4565-8787-989898989898",
    "raw_hash": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "parser_version": "manual/1",
    "source_operation_id": null,
    "row": null
  },
  "relation": "None",
  "confidence": "Estimated",
  "idempotency_key": null
}"#;

#[test]
fn an_event_recorded_before_the_field_existed_still_reads() {
    // The default is “unknown” for every item. This is not a stub:
    // the event genuinely asserted none of the listed facts,
    // and assigning Known to it would retroactively declare as
    // documented something that nobody had seen.
    let event: Event = serde_json::from_str(RECORDED_AT_VERSION_TWO)
        .expect("version 2 event must be readable without migration");
    assert_eq!(event.schema_version, 2);

    let EventKind::OpeningPosition { assertions, .. } = event.kind else {
        panic!("expected a reconstructed opening");
    };
    assert_eq!(assertions, OpeningAssertions::default());
    assert_eq!(assertions.quantity, Certainty::Estimated);
    assert_eq!(assertions.acquisition_date, None);
    assert_eq!(
        assertions.acquisition_date_certainty,
        DateCertainty::Unknown
    );
    assert_eq!(assertions.tax_basis, BasisCertainty::Unknown);
    assert_eq!(assertions.basis_currency, None);
    assert_eq!(assertions.basis_rate, None);
    assert_eq!(assertions.fees_included, Tristate::Unknown);
    assert_eq!(assertions.ldv_eligibility, Knowledge::Unknown);
    assert_eq!(assertions.prior_corporate_actions, Knowledge::Unknown);
    assert!(
        !assertions.basis_is_documented(),
        "the tax basis does not become documented merely because \
	         the event is old"
    );
}

#[test]
fn a_documented_basis_is_the_only_thing_that_reports_as_documented() {
    // §10.7: if the tax basis is unknown, the tax report
    // returns a range or not_computable, rather than an exact figure.
    // The indicator must distinguish three states, not two.
    for (certainty, documented) in [
        (BasisCertainty::Documented, true),
        (BasisCertainty::Estimated, false),
        (BasisCertainty::Unknown, false),
    ] {
        let assertions = OpeningAssertions {
            tax_basis: certainty,
            ..OpeningAssertions::default()
        };
        assert_eq!(
            assertions.basis_is_documented(),
            documented,
            "basis {certainty:?} was assessed incorrectly"
        );
    }
}

#[test]
fn assertions_survive_a_round_trip() {
    // Assertions are written to the log and read back from it: a variant
    // that does not survive serialization will be detected when reading the history.
    let assertions = OpeningAssertions {
        quantity: Certainty::Known,
        acquisition_date: Some(time::macros::date!(2021 - 06 - 15)),
        acquisition_date_certainty: DateCertainty::Known,
        tax_basis: BasisCertainty::Documented,
        basis_currency: Some(iaam_core::money::CurrencyCode::Usd),
        basis_rate: Some(iaam_core::numeric::decimal::Dec::one()),
        fees_included: Tristate::Yes,
        ldv_eligibility: Knowledge::Known,
        prior_corporate_actions: Knowledge::Known,
    };
    let json = serde_json::to_string(&assertions).expect("serialization");
    let back: OpeningAssertions = serde_json::from_str(&json).expect("parse");
    assert_eq!(back, assertions);
}
