#!/usr/bin/env bash
# Install the repository's git hooks.
#
# The privacy guard runs in `make check`, which catches a value before it is
# pushed. The hook catches it before it enters a commit at all — and the
# difference is a history rewrite, which this project has already paid for once.
#
# WHERE THE HOOK GOES, AND WHY IT IS NOT `.git/hooks`
#
# This script used to write `.git/hooks/pre-commit` and print "installed". Beads
# sets `core.hooksPath` to `.beads/hooks`, and once that is set git does not read
# `.git/hooks` at all — so the guard never ran on a single commit, and the only
# surviving run was inside `make check`, after the value was already committed
# (iaam-rq4h). An installer that reports a hook git will not consult is worse
# than no installer, because it retires the vigilance that would replace it.
#
# So the hook is installed into the directory git ACTUALLY consults, resolved
# from `core.hooksPath`, and it is composed into whatever is already there
# rather than overwriting it — taking `core.hooksPath` back from beads would fix
# our guard by dropping theirs.
#
# `.beads/hooks/pre-commit` is generated by `bd hooks install` and is tracked.
# The seam that survives regeneration is beads' own: `bd hooks install` states,
# and this project verified, that content OUTSIDE its section markers is
# preserved across installs and upgrades. Our block therefore sits after the
# beads END marker — after, not before, because the beads hook may add its own
# export to the index, and the guard must read the index as it will be committed.
#
# The block is committed with the file, so a fresh clone carries it before this
# script has ever run; this script's remaining job is to make sure git is
# looking at a directory that has it.
set -euo pipefail

REPO_ROOT=$(git -C "$(dirname -- "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)
cd "$REPO_ROOT"

MARK_BEGIN='# --- BEGIN IAAM PRIVACY GUARD (iaam-rq4h) ---'

# What this script wrote before iaam-rq4h. It ends in `exec`, so anything
# appended after it would never run — the one way this installer could report
# success and still be inert. It is ours, it is superseded, so it is removed.
LEGACY_EXEC='exec "$ROOT/scripts/check-no-personal-data.sh"'

IFS= read -r -d '' GUARD_BLOCK <<'BLOCK' || true

# --- BEGIN IAAM PRIVACY GUARD (iaam-rq4h) ---
# Managed by scripts/install-hooks.sh. Kept OUTSIDE the beads section markers on
# purpose: beads preserves content outside them, so this survives `bd hooks
# install` regenerating the file. Do not move it inside the markers.
_iaam_root=$(git rev-parse --show-toplevel) || exit 1
if [ ! -x "$_iaam_root/scripts/check-no-personal-data.sh" ]; then
  echo "PRIVACY: scripts/check-no-personal-data.sh is missing or not executable." >&2
  echo "        Refusing the commit: a guard that cannot run must not pass." >&2
  exit 1
fi
"$_iaam_root/scripts/check-no-personal-data.sh" --staged || exit 1
# --- END IAAM PRIVACY GUARD (iaam-rq4h) ---
BLOCK

# Add the guard block to one pre-commit file, leaving everything else in it
# alone. Idempotent: a file that already carries the markers is not touched.
ensure_guard() {
  local hook="$1"
  mkdir -p "$(dirname -- "$hook")"
  if [ ! -e "$hook" ]; then
    printf '%s\n' '#!/usr/bin/env sh' > "$hook"
  fi
  if grep -Fq "$MARK_BEGIN" "$hook"; then
    chmod +x "$hook"
    return 1  # already present; nothing added
  fi
  if grep -Fq "$LEGACY_EXEC" "$hook"; then
    grep -Fvx "$LEGACY_EXEC" "$hook" > "$hook.iaam-tmp"
    mv "$hook.iaam-tmp" "$hook"
  fi
  # Any remaining `exec` would swallow what we are about to append, and quietly
  # appending under one is exactly the failure this bead exists to end.
  if grep -qE '^[[:space:]]*exec[[:space:]]' "$hook"; then
    echo "HOOKS: $hook ends in an exec; the guard appended after it would never run." >&2
    echo "        Move that exec to the end of the file, then re-run make hooks." >&2
    exit 1
  fi
  printf '%s\n' "$GUARD_BLOCK" >> "$hook"
  chmod +x "$hook"
  return 0
}

# The directory git consults for hooks. `core.hooksPath` wins when set; a
# relative value is read relative to the top of the working tree.
hooks_dir=$(git config --get core.hooksPath || true)
if [ -z "$hooks_dir" ]; then
  hooks_dir="$(git rev-parse --git-dir)/hooks"
fi
case "$hooks_dir" in
  /*) ;;
  *) hooks_dir="$REPO_ROOT/$hooks_dir" ;;
esac
active_hook="$hooks_dir/pre-commit"

if ensure_guard "$active_hook"; then
  echo "installed: $active_hook"
else
  echo "already present: $active_hook"
fi

# Belt and braces. `bd hooks install --beads` points core.hooksPath at
# .beads/hooks; if that has not happened yet in this clone, the guard would be
# silently dropped the day it does. Seeding the beads hook now means the switch
# cannot lose it.
beads_hook="$REPO_ROOT/.beads/hooks/pre-commit"
if [ -e "$beads_hook" ] && [ "$beads_hook" != "$active_hook" ]; then
  if ensure_guard "$beads_hook"; then
    echo "also seeded: $beads_hook (used if beads takes over core.hooksPath)"
  fi
fi

# The same for a leftover `.git/hooks/pre-commit`: inert while core.hooksPath is
# set, and live again the moment anyone unsets it. Say that it is inert, and
# leave the guard in it so that day is not the day the guard disappears.
legacy_hook="$REPO_ROOT/.git/hooks/pre-commit"
if [ "$legacy_hook" != "$active_hook" ] && [ -e "$legacy_hook" ]; then
  echo "note: $legacy_hook is INERT — core.hooksPath points elsewhere."
  if ensure_guard "$legacy_hook"; then
    echo "      seeded anyway, in case core.hooksPath is ever unset."
  fi
fi

# --- The installer proves what it claims -------------------------------------
# "installed" is a claim about a future commit. Check it now, and fail loudly
# rather than print a reassuring line nobody will re-examine.
fail=0
if [ ! -x "$active_hook" ]; then
  echo "HOOKS: $active_hook is not executable — git will not run it." >&2
  fail=1
fi
if ! grep -Fq "$MARK_BEGIN" "$active_hook" 2>/dev/null; then
  echo "HOOKS: the privacy guard is not present in $active_hook." >&2
  fail=1
fi
if ! sh -n "$active_hook" 2>/dev/null; then
  echo "HOOKS: $active_hook is not a valid shell script." >&2
  fail=1
fi
# Run the guard exactly as the hook will. A refusal here is the guard working —
# something statement-shaped is staged right now — so only an inability to
# execute it counts as a failed install. The two are distinguished by exit code:
# 126/127 is the shell failing to run the file, anything else is a verdict.
guard_rc=0
guard_out=$(./scripts/check-no-personal-data.sh --staged 2>&1) || guard_rc=$?
if [ "$guard_rc" -ge 126 ] || [ -z "$guard_out" ]; then
  echo "HOOKS: the guard did not run (exit $guard_rc):" >&2
  printf '%s\n' "$guard_out" >&2
  fail=1
elif [ "$guard_rc" -ne 0 ]; then
  echo "note: the guard currently REFUSES what is staged — it ran, and it objects:"
  printf '%s\n' "$guard_out"
fi
if [ "$fail" -ne 0 ]; then
  echo "HOOKS: refused. The privacy guard is NOT in force." >&2
  exit 1
fi
echo "verified: git reads $hooks_dir, and the privacy guard runs there."
